### ISSUE TITLE
Unittests are failing on python 3.8

### ISSUE THREAD

**Issue by woutervb** [canonical-ols/acceptable#103]
Running on a focal system, with python 3.7 installed from the deadsnakes ppa, I updated tox to also test the python3.7 and 3.8 interpreters.
The python 3.7 works fine, but the python 3.8 is having some failed unittests.

Most (all?) seem to be related by an offset in the generated files, which cause a off by one error. I.e. results are expected on line 11, but are now found on line 12. I do think is only affects the tests and not the actual code.

**Comment by nessita** [comment]
I did some research and this is caused by https://bugs.python.org/issue38283:

"sys._getframe(1).f_lineno changed behavior in 3.8"

I'm currently trying to think of a workaround/proper fix.
