### ISSUE TITLE
Create test doubles from JSON, not AST

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-ols/acceptable#75]
The test doubles that acceptable creates use AST parsing to try and understand what the schema is for a given API endpoint, but this is limited and hard to do without duplicating a full blown Python interpreter.

There should be enough information in the `api.json` files that `acceptable` creates to correctly create the test doubles, and allow doubles to be created on APIs that AST parsing fails on.

**Comment by tonysimpson** [comment]
This has been implemented and released.
